import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import globals from 'globals'

// Generated by `wxt prepare`. Declares the auto-imported names (storage,
// defineBackground, browser, the React hooks, ...) as globals so they don't
// trip no-undef.
import wxtAutoImports from './.wxt/eslint-auto-imports.mjs'

export default tseslint.config(
    {
        ignores: ['.output/', '.wxt/', 'node_modules/', 'public/'],
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    wxtAutoImports,
    {
        files: ['**/*.{ts,tsx}'],
        languageOptions: {
            globals: {
                ...globals.browser,
            },
            parserOptions: {
                ecmaFeatures: { jsx: true },
            },
        },
        rules: {
            // Prefix with _ to silence: useful for handlers stubbed out ahead
            // of their implementation.
            '@typescript-eslint/no-unused-vars': [
                'error',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                    caughtErrorsIgnorePattern: '^_',
                },
            ],
        },
    },
    {
        files: ['**/*.tsx'],
        // `configs.recommended` and `configs['recommended-latest']` are still
        // eslintrc format in v7; only `configs.flat.*` are flat config.
        ...reactHooks.configs.flat.recommended,
    },
)
